CLJ Impl
formcept/whiteboard pull request #2
Opened 2017-06-30 07:25 UTC by punit-naik

# Status
Please select the status of this PR-

- [x] Ready to review and merge
- [ ] Commits pending
- [ ] On Hold

# Committer Checklist
Overview of the changes proposed in this PR.

## Changes Proposed
Added Clojure - Onyx Implementations

## Test Results
N/A

## Related PRs
N/A

## Documentation
N/A

# Reviewer Checklist
Please validate and mark the readiness of this PR based on these validations-

## Pre-requisites
- [ ] Follows [Coding Style](https://formcept.atlassian.net/wiki/display/DEV/Developer+Handbook#DeveloperHandbook-CodingStyleGuide)
- [ ] Follows [Development Workflow](https://formcept.atlassian.net/wiki/display/DEV/Developer+Handbook#DeveloperHandbook-DevelopmentWorkflow) and targets the right branch
- [ ] Follows [Commit Message Guidelines](https://formcept.atlassian.net/wiki/display/DEV/Developer+Handbook#DeveloperHandbook-Commit)
- [ ] Has an associated JIRA ID and the same has been mentioned in the PR title

## Change Checklist
- [ ] PR contains only the changes expected in the mentioned JIRA ticket(s)
- [ ] Test Cases have been added
- [ ] Changes have been documented in code and/or Confluence

2017-06-30 07:26 UTC, punit-naik commented
@anujsrc How does this look?

2017-06-30 09:10 UTC, anujsrc requested changes

2017-06-30 09:10 UTC, anujsrc commented on clojure/build.sh
> +cd onyx-impl
@punit-naik - lets keep the top-level folder name as the platform name. So, change this to ``onyx``.

2017-06-30 09:10 UTC, anujsrc commented on clojure/onyx-impl/README.md
> +ML-Onyx
Change to just ``Onyx``

2017-06-30 09:10 UTC, anujsrc commented on clojure/onyx-impl/build.sh
> +echo -e "Building Onyx Implementations..."
Just say ``Onyx``

2017-06-30 09:10 UTC, anujsrc commented on clojure/onyx-impl/locality-sensitive-hashing/README.md
> +# lsh
Change to full-form- ``Locality Sensitive Hashing (LSH)``

2017-06-30 09:10 UTC, anujsrc commented on clojure/onyx-impl/onyx-utils/README.md
> +# onyx-utils
Change to ``Onyx Utilities``

2017-06-30 09:10 UTC, anujsrc commented on clojure/onyx-impl/locality-sensitive-hashing/src/org/formcept/onyx/lsh_onyx/core.clj
> +(ns org.formcept.onyx.lsh-onyx.core
Add FC License Header-

```
;;
;; Copyright (c) 2011-onwards, FORMCEPT [http://www.formcept.com]
;; All rights reserved.
;;
;; NOTICE:  All information contained herein is, and remains
;; the property of FORMCEPT and its suppliers, if any.
;; The intellectual and technical concepts contained
;; herein are proprietary to FORMCEPT and its suppliers and
;; may be covered by U.S. and Foreign Patents, patents in process,
;; and are protected by trade secret or copyright law. Dissemination
;; of this information or reproduction of this material
;; is strictly forbidden unless prior written permission is obtained
;; from FORMCEPT.
;;
```

2017-06-30 09:10 UTC, anujsrc commented on clojure/onyx-impl/onyx-utils/src/org/formcept/onyx/onyx_utils/aggregation/core.cljc
> +(ns org.formcept.onyx.onyx-utils.aggregation.core)
Add FC License Header-

```
;;
;; Copyright (c) 2011-onwards, FORMCEPT [http://www.formcept.com]
;; All rights reserved.
;;
;; NOTICE:  All information contained herein is, and remains
;; the property of FORMCEPT and its suppliers, if any.
;; The intellectual and technical concepts contained
;; herein are proprietary to FORMCEPT and its suppliers and
;; may be covered by U.S. and Foreign Patents, patents in process,
;; and are protected by trade secret or copyright law. Dissemination
;; of this information or reproduction of this material
;; is strictly forbidden unless prior written permission is obtained
;; from FORMCEPT.
;;
```

2017-06-30 09:10 UTC, anujsrc commented on clojure/onyx-impl/onyx-utils/src/org/formcept/onyx/onyx_utils/string_utils/core.clj
> +(ns org.formcept.onyx.onyx-utils.string-utils.core
Add FC License Header-

```
;;
;; Copyright (c) 2011-onwards, FORMCEPT [http://www.formcept.com]
;; All rights reserved.
;;
;; NOTICE:  All information contained herein is, and remains
;; the property of FORMCEPT and its suppliers, if any.
;; The intellectual and technical concepts contained
;; herein are proprietary to FORMCEPT and its suppliers and
;; may be covered by U.S. and Foreign Patents, patents in process,
;; and are protected by trade secret or copyright law. Dissemination
;; of this information or reproduction of this material
;; is strictly forbidden unless prior written permission is obtained
;; from FORMCEPT.
;;
```

2017-06-30 09:11 UTC, anujsrc commented
@punit-naik - change the commit message and PR title to ``Onyx LSH``

2017-06-30 09:38 UTC, punit-naik commented on clojure/build.sh
> +cd onyx-impl
Done.

2017-06-30 09:39 UTC, punit-naik commented on clojure/onyx-impl/README.md
> +ML-Onyx
Done.

2017-06-30 09:39 UTC, punit-naik commented on clojure/onyx-impl/build.sh
> +echo -e "Building Onyx Implementations..."
Done.

2017-06-30 09:39 UTC, punit-naik commented on clojure/onyx-impl/locality-sensitive-hashing/README.md
> +# lsh
Done.

2017-06-30 09:39 UTC, punit-naik commented on clojure/onyx-impl/onyx-utils/README.md
> +# onyx-utils
Done.

2017-06-30 09:39 UTC, punit-naik commented on clojure/onyx-impl/locality-sensitive-hashing/src/org/formcept/onyx/lsh_onyx/core.clj
> +(ns org.formcept.onyx.lsh-onyx.core
Done, thanks for the input.

2017-06-30 09:39 UTC, punit-naik commented on clojure/onyx-impl/onyx-utils/src/org/formcept/onyx/onyx_utils/aggregation/core.cljc
> +(ns org.formcept.onyx.onyx-utils.aggregation.core)
Done, thanks for the input.

2017-06-30 09:39 UTC, punit-naik commented on clojure/onyx-impl/onyx-utils/src/org/formcept/onyx/onyx_utils/string_utils/core.clj
> +(ns org.formcept.onyx.onyx-utils.string-utils.core
Done, thanks for the input.

2017-06-30 09:40 UTC, punit-naik commented
@anujsrc I have done all the changes you requested.

2017-07-02 16:03 UTC, anujsrc commented
@punit-naik - rename the commit to ``Onyx LSH``. Also, fix these warnings-

```
Warning: specified :main without including it in :aot. 
Implicit AOT of :main will be removed in Leiningen 3.0.0. 
If you only need AOT for your uberjar, consider adding :aot :all into your
:uberjar profile instead.
Compiling org.formcept.onyx.lsh-onyx.core
log4j:WARN No appenders could be found for logger (com.amazonaws.AmazonWebServiceClient).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

2017-07-03 17:22 UTC, anujsrc commented
@punit-naik - please sync with base branch and check the Travis build

2017-07-04 09:39 UTC, closed without merging